[build]
  publish = "."
  command = "echo 'No build step needed'"

[[redirects]]
  from = "/api/*"
  to = "https://tbs-production-9ec7.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
