[build]
  publish = "."
  command = "echo 'No build step needed'"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://api.open-meteo.com https:; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data: https:; connect-src 'self' https://tbs-production-9ec7.up.railway.app https://api.open-meteo.com https:; font-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self';"

[[redirects]]
  from = "/api/*"
  to = "https://tbs-production-9ec7.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
